//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 10:12:27 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/testplan", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ms.mcs.model.testplan.xsdschema;
