//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 10:12:27 PM EDT 
//


package ms.mcs.model.testplan.xsdschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestSuites complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestSuites"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="exec" type="{http://www.example.org/testplan}Execution"/&gt;
 *         &lt;element name="testSuite" type="{http://www.example.org/testplan}TestSuite" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestSuites", propOrder = {
    "exec",
    "testSuites"
})
@XmlRootElement(name = "testSuites")
public class TestSuites {

    @XmlElement(required = true)
    protected Execution exec;
    @XmlElement(name = "testSuite", required = true)
    protected List<TestSuite> testSuites;

    /**
     * Gets the value of the exec property.
     * 
     * @return
     *     possible object is
     *     {@link Execution }
     *     
     */
    public Execution getExec() {
        return exec;
    }

    /**
     * Sets the value of the exec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Execution }
     *     
     */
    public void setExec(Execution value) {
        this.exec = value;
    }

    /**
     * Gets the value of the testSuites property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testSuites property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestSuites().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestSuite }
     * 
     * 
     */
    public List<TestSuite> getTestSuites() {
        if (testSuites == null) {
            testSuites = new ArrayList<TestSuite>();
        }
        return this.testSuites;
    }

}
