//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 10:12:27 PM EDT 
//


package ms.mcs.model.testplan.xsdschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestCaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestCaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="testType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="desc" type="{http://www.example.org/testplan}TestTypeDesc" maxOccurs="11"/&gt;
 *         &lt;element name="passed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestCaseType", propOrder = {
    "testType",
    "descs",
    "passed"
})
@XmlRootElement(name = "testCase")
public class TestCase {

    @XmlElement(required = true)
    protected String testType;
    @XmlElement(name = "desc", required = true)
    @XmlSchemaType(name = "string")
    protected List<TestTypeDesc> descs;
    protected boolean passed;

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestType(String value) {
        this.testType = value;
    }

    /**
     * Gets the value of the descs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestTypeDesc }
     * 
     * 
     */
    public List<TestTypeDesc> getDescs() {
        if (descs == null) {
            descs = new ArrayList<TestTypeDesc>();
        }
        return this.descs;
    }

    /**
     * Gets the value of the passed property.
     * 
     */
    public boolean isPassed() {
        return passed;
    }

    /**
     * Sets the value of the passed property.
     * 
     */
    public void setPassed(boolean value) {
        this.passed = value;
    }

}
